---
title: Basil Labs
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Basil Labs
email: connect@basillabs.org
address: 745 ATLANTIC AVENUE, BOSTON MA
tagline: Basil Labs
description: Basil Labs helps your organization understand your consumers, innovate
  and outpace the competition.
baseurl: ''
url: http://127.0.0.1:4000/
paginate: 12
paginate_path: "/blog/page:num/"
markdown: kramdown
plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-include-cache
google_analytics: ''
disqus:
  shortname: ''
hero: hero_sass_background_image
hero_sass_name: We Made our <br> Software 100% Errorless
hero_sass_text: The first is a non technical method which requires the use of adware
  removal software. Download free adware and spyware removal software and use advanced
  tools to help prevent getting infected.
hero_sass_image: img/hero/hero-img.png
hero_sass_btn_one_link: "#"
hero_sass_btn_one_text: Start a project
hero_sass_btn_two_link: "#"
hero_sass_btn_two_text: " View Pricing "
hero_saas_video_name: We Made our <br> Software 100% Errorless
hero_saas_video_text: The first is a non technical method which requires the use of
  adware removal software.  Download free adware and spyware removal software and
  use advanced tools to help prevent  getting infected.
hero_saas_video_image: img/mockup.png
hero_saas_video_video: vdo/sass-bv.mp4
hero_saas_video_btn_one_link: "#"
hero_saas_video_btn_one_text: Browse free demo
hero_sass_background_image_name: We Made our <br> Software 100% Errorless
hero_sass_background_image_text: The first is a non technical method which requires
  the use of adware removal software.  Download free adware and spyware removal software
  and use advanced tools to help prevent  getting infected.
hero_sass_background_image_image: img/hero/hero-img.png
hero_sass_background_image_btn_one_link: "#"
hero_sass_background_image_btn_one_text: Browse free demo
hero_saas_fixed_image_name: We Made our <br> Software 100% Errorless
hero_saas_fixed_image_text: The first is a non technical method which requires the
  use of adware removal software.  Download free adware and spyware removal software
  and use advanced tools to help prevent  getting infected.
hero_saas_fixed_image_image: img/mockup.png
hero_saas_fixed_image_btn_one_link: "#"
hero_saas_fixed_image_btn_one_text: Browse free demo
hero_sass_slider_name: We Made our <br> Software 100% Errorless
hero_sass_slider_image: img/mockup.png
hero_sass_slider_btn_one_link: "#"
hero_sass_slider_btn_one_text: Browse free demo
hero_sass_slider:
- image: img/carusel/s1.jpg
- image: img/carusel/s2.jpg
- image: img/carusel/s3.jpg
hero_product_name: The most Creative <br> Theme ever for Business
hero_product_text: The first is a non technical method which requires the use of adware
  removal software. Download  free adware and spyware removal software and use advanced
  tools to help prevent getting infected.
hero_product_image: img/hero/hero-img2.png
hero_product_btn_one_link: "#"
hero_product_btn_one_text: Browse free demo
hero_product_video_name: The most Creative <br> Theame ever in Business
hero_product_video_text: The first is a non technical method which requires the use
  of adware removal software. ownload free adware and spyware removal
hero_product_video_image: img/iPhoneX.png
hero_product_video_video: vdo/app-bv.mp4
hero_product_video_btn_one_link: "#"
hero_product_video_btn_one_text: Browse free demo
hero_product_background_image_name: The most Creative <br> Theame ever in Business
hero_product_background_image_text: The first is a non technical method which requires
  the use of adware removal software. Download free adware and spyware removal software
  and use advanced tools to help prevent getting infected.
hero_product_background_image_image: img/iPhoneX.png
hero_product_background_image_btn_one_link: "#"
hero_product_background_image_btn_one_text: Browse free demo
hero_product_fixed_image_name: The most Creative <br> Theame ever in Business
hero_product_fixed_image_text: The first is a non technical method which requires
  the use of adware removal software.  Download free adware and spyware removal software
  and use advanced tools to help prevent  getting infected.
hero_product_fixed_image_image: img/iPhoneX.png
hero_product_fixed_image_btn_one_link: "#"
hero_product_fixed_image_btn_one_text: Browse free demo
hero_product_slider_name: The most Creative <br> Theame ever in Business
hero_product_slider_text: The first is a non technical method which requires the use
  of adware removal software. Download free adware and spyware removal software and
  use advanced tools to help prevent getting infected.
hero_product_slider_image: img/iPhoneX.png
hero_product_slider_btn_one_link: "#"
hero_product_slider_btn_one_text: Browse free demo
hero_product_slider:
- image: img/carusel/a1.jpg
- image: img/carusel/a2.jpg
- image: img/carusel/a3.jpg
hero_blog_slider:
- image: img/hero/hero-blog.jpg
  author: Sir Alex James
  title: The Idea Of God Is <br /> Not Henceforth Relevant
  category: Technical
- image: img/hero/hero-blog.jpg
  author: Sir Alex James
  title: The Idea Of God Is <br /> Not Henceforth Relevant
  category: Art &amp; Fantacy
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
whitelist:
- jekyll-sitemap
- jekyll-feed
- jekyll-include-cache
feature_image_one: img/feature/i1.png
feature_title_one: Collaboration
feature_description_one: Some days a motivational quote can provide a quick pick-me-up
  for employees and even  management.
feature_image_two: img/feature/i3.png
feature_title_two: Full of features
feature_description_two: Some days a motivational quote can provide a quick pick-me-up
  for employees and even management.
feature_image_three: img/feature/i4.png
feature_title_three: Global Framework
feature_description_three: Some days a motivational quote can provide a quick pick-me-up
  for employees and even management.
marketing_title: Build Your Brand  Automate Your Marketing
marketing_description: The first is a non technical method which requires the use
  of adware removal software. Download free adware and spyware removal software and
  use advanced tools to help prevent getting infected. Spyware scan review is a free
  service for anyone interested in downloading spyware/adware removal software. Our
  adware remover is the most trusted.
marketing_image_one: "/img/marketing/dashboards.png"
marketing_image_two: "/img/marketing/dashboards.png"
marketing_btn_text: Browse free demo
marketing_btn_link: "#"
statistics_title: We glow with Our Statistics
statistics_description: The first is a non technical method which requires the use
  of adware removal software. Download free adware and spyware removal software and
  use advanced tools getting infected.
statistics_image: img/title-icon.png
statistics_start_image: img/title-icon.png
statistics_item_one_image: img/stat/s1.png
statistics_item_one_title: Productivity
statistics_item_one_link: "#"
statistics_item_one_description: Making changes in your life is great and it is the
  way we grow and develop as people. Change is a constant.
statistics_item_two_image: img/stat/s2.png
statistics_item_two_title: Sales Monitoring
statistics_item_two_link: "#"
statistics_item_two_description: Making changes in your life is great and it is the
  way we grow and develop as people. Change is a constant.
statistics_item_three_image: img/stat/s2.png
statistics_item_three_title: Payment Stats
statistics_item_three_link: "#"
statistics_item_three_description: Making changes in your life is great and it is
  the way we grow and develop as people. Change is a constant.
statistics_item_four_image: img/stat/s4.png
statistics_item_four_title: Pending Clearnance
statistics_item_four_link: "#"
statistics_item_four_description: Making changes in your life is great and it is the
  way we grow and develop as people. Change is a constant.
cta_title: Fallen in Love with <br> our features? Get a free trial for 14 days!
cta_btn_link_one: "#"
cta_btn_text_one: Start free trial
cta_btn_link_two: "#"
cta_btn_text_two: Signup
social_title: Manage Social Network with Our Managing Toolkit
social_description: The first is a non technical method which requires the use of
  adware removal software. Download free adware and spyware removal software and use
  advanced tools to help prevent getting infected. Spyware scan review is a free service
  for anyone interested in downloading spyware/adware removal software. Our adware
  remover is the most trusted.
social_image: img/social-img.png
social_button_text: Browse free demo
social_button_link: "#"
pricing-table-title: Select your Best Pricing
pricing-table-description: 'The first is a non technical method which requires the
  use of adware removal software. Download free adware and spyware removal software
  and use advanced tools getting infected. '
plan-starter-name: starter
plan-starter-tagline: Small business holders
plan-starter-price: "<span>£29</span>/mo"
plan-starter-offer-line-1-info: 2 User permission
plan-starter-offer-line-2-info: Customization Allowed
plan-starter-offer-line-3-info: Social media tool Enabled
plan-starter-offer-line-4-info: No Online Support
plan-starter-offer-line-5-info: 6 Months Backup
plan-starter-url: "#"
plan-starter-btn_text: Get Started
plan-standard-name: standard
plan-standard-tagline: Small business holders
plan-standard-price: "<span>£49</span>/mo"
plan-standard-offer-line-1-info: 2 User permission
plan-standard-offer-line-2-info: Customization Allowed
plan-standard-offer-line-3-info: Social media tool Enabled
plan-standard-offer-line-4-info: No Online Support
plan-standard-offer-line-5-info: 6 Months Backup
plan-standard-url: "#"
plan-standard-btn_text: Get Started
plan-business-name: premium
plan-business-tagline: Small business holders
plan-business-price: "<span>£99</span>/mo"
plan-business-offer-line-1-info: 2 User permission
plan-business-offer-line-2-info: Customization Allowed
plan-business-offer-line-3-info: Social media tool Enabled
plan-business-offer-line-4-info: No Online Support
plan-personal-offer-line-5-info: 6 Months Backup
plan-business-url: "#"
plan-business-btn_text: Get Started
unique_feature_title: Features that make us Stand Out
unique_feature_description: The first is a non technical method which requires the
  use of adware removal software. Download free adware and spyware removal software
  and use advanced tools getting infected.
unique_feature_image: img/unique_feature.png
unique_feature_main_image_slider:
- image: img/carusel/c1.png
- image: img/carusel/c2.png
- image: img/carusel/c3.png
unique_feature_section_one_title: Certifications
unique_feature_section_one_description: We all live in an age that belongs to the
  young at heart. Life that is becoming extremely fast, day to day, also asks us to
  remain.
unique_feature_section_one_image: http://127.0.0.1:4000/img/feature/f1.png
unique_feature_section_one_link: "#"
unique_feature_section_two_title: Page Builder
unique_feature_section_two_description: Vera sought out counseling with me because
  her doctor advised her to discover the emotional causes of her chronic fatigue.
unique_feature_section_two_image: http://127.0.0.1:4000/img/feature/f2.png
unique_feature_section_two_link: "#"
bands_slider:
- image: img/brands/b1.png
  link: "#"
- image: img/brands/b2.png
  link: "#"
- image: img/brands/b3.png
  link: "#"
- image: img/brands/b4.png
  link: "#"
- image: img/brands/b5.png
  link: "#"
- image: img/brands/b6.png
  link: "#"
- image: img/brands/b7.png
  link: "#"
- image: img/brands/b8.png
  link: "#"
- image: img/brands/b9.png
  link: "#"
- image: img/brands/b10.png
  link: "#"
testimonials:
- author: Travor James
  avatar: "/img/review/user.png"
  position: Head of Marketing, Apple Inc.
  quotes: Who are in extremely love with eco friendly system. Lorem ipsum dolor sit
    amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
    et dolore magna aliqua.
- author: Travor James
  avatar: "/img/review/user.png"
  position: Head of Marketing, Apple Inc.
  quotes: Who are in extremely love with eco friendly system. Lorem ipsum dolor sit
    amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
    et dolore magna aliqua.
- author: Travor James
  avatar: "/img/review/user.png"
  position: Head of Marketing, Apple Inc.
  quotes: Who are in extremely love with eco friendly system. Lorem ipsum dolor sit
    amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
    et dolore magna aliqua.
- author: Travor James
  avatar: "/img/review/user.png"
  position: Head of Marketing, Apple Inc.
  quotes: Who are in extremely love with eco friendly system. Lorem ipsum dolor sit
    amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
    et dolore magna aliqua.
- author: Travor James
  avatar: "/img/review/user.png"
  position: Head of Marketing, Apple Inc.
  quotes: Who are in extremely love with eco friendly system. Lorem ipsum dolor sit
    amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
    et dolore magna aliqua.
- author: Travor James
  avatar: "/img/review/user.png"
  position: Head of Marketing, Apple Inc.
  quotes: Who are in extremely love with eco friendly system. Lorem ipsum dolor sit
    amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
    et dolore magna aliqua.
blog-title: Latest Posts from our Blog
blog-description: The first is a non technical method which requires the use of adware
  removal software. Download free adware and spyware removal software and use advanced
  tools getting infected.
contact_title: Whenever You Need, Just Send a Message
contact_description: The first is a non technical method which requires the use of
  adware removal software. Download free adware and spyware removal software and use
  advanced tools getting infected.
contact_image: img/title-icon.png
contact_email: support@demo.com
contact_phone: 00 (440) 9865 562 9865
contact_address: Los Angeles, United States
footer_title: About Us
footer_description: Basil Labs helps organizations tap into digital and in store consumer intelligence to craft stronger brands and target their audiences with pinpoint accuracy.
footer_resources_link_heading: Resources
footer_resources_link_one_text: Guides
footer_resources_link_one_link: "#"
footer_resources_link_two_text: Research
footer_resources_link_three_text: Experts
footer_resources_link_four_text: Agencies
footer_features_link_heading: Features
footer_features_link_one_text: Guides
footer_features_link_one_link: "#"
footer_features_link_two_text: Research
footer_features_link_three_text: Experts
footer_features_link_four_text: Agencies
footer_facebook_link: "#"
footer_twitter_link: "#"
footer_dribbble_link: "#"
footer_behance_link: "#"
mailchimp:
  user-id: 
  list-id: 
copyright_text: Copyright © 2019 All rights reserved to
company_url: "#"
google_site_verification: 
bing_site_verification: 
yandex_site_verification: 
naver_site_verification: 
twitter:
  username: 
facebook:
  username: 
  app_id: 
  publisher: 
og_image: 
social:
  type: 
  name: 
  links: 
analytics:
  provider: false
  google:
    tracking_id: 
    anonymize_ip: 
map: AIzaSyA7nx22ZmINYk9TGiXDEXGVxghC43Ox6qA
